fix jest setup

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -43,8 +43,13 @@ jobs:
           folder: build 
 
       - name: Run unit tests
-        run: npm run test
+        run: npm run test:ci
 
       - name: Test Reporter
         uses: dorny/test-reporter@v1.7.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
             
